### PR TITLE
Some Basic SEO Optimizations

### PR DESCRIPTION
**Pull request by ChargedByte**
Added some basic SEO optimizations.

Meta Tags:
Keywords
Description
Author

Minified:
CSS

Images:
ALT tags

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
why minified when it's supposed to be clean for contribution? 🤔

**Comment by ChargedByte** [comment]
Well minified is better for loading times.

**Comment by AlexFlipnote** [comment]
I don't think anyone will struggle with ~100KB
Image

**Comment by ChargedByte** [comment]
True to be honest.

**Comment by AlexFlipnote** [comment]
revert it and PR shall be fine

**Comment by ChargedByte** [comment]
Done. CSS unminified.

**Pull request merged**
